name: knn_dart

environment:
    sdk: ">=2.7.0 <3.0.0"

dependencies:
    test: ^1.15.4
    flutter:
        sdk: flutter
        
    http: ^0.12.1  
    
      # The following adds the Cupertino Icons font to your application.
      # Use with the CupertinoIcons class for iOS style icons.
    cupertino_icons: ^0.1.3
    
# dev_dependencies:
#     flutter_test:
#     #sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

    # The following line ensures that the Material Icons font is
    # included with your application, so that you can use the icons in
    # the material Icons class.
    uses-material-design: true